# Generated by Django 6.0.6 on 2026-06-28 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("rut", models.CharField(blank=True, max_length=20, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("url", models.URLField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("mantenimiento", "En mantenimiento"),
                        ],
                        default="activo",
                        max_length=30,
                    ),
                ),
                ("fecha_despliegue", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Entorno",
                "verbose_name_plural": "Entornos",
            },
        ),
        migrations.CreateModel(
            name="ClienteUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="projects.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clientes_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Cliente-Usuario",
                "verbose_name_plural": "Asignaciones Cliente-Usuario",
                "unique_together": {("cliente", "usuario")},
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="usuarios",
            field=models.ManyToManyField(
                blank=True,
                related_name="clientes",
                through="projects.ClienteUsuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EnvironmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("desplegado", "Desplegado"),
                        ],
                        default="pendiente",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entorno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="projects.environment",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_entorno",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Entorno",
                "verbose_name_plural": "Solicitudes de Entorno",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("mensaje", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("exito", "Éxito"),
                            ("advertencia", "Advertencia"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("leida", models.BooleanField(default=False)),
                ("url", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("pausado", "Pausado"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="activo",
                        max_length=50,
                    ),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos",
                        to="projects.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KanbanColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="#0d6efd", max_length=7)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columnas_kanban",
                        to="projects.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Columna Kanban",
                "verbose_name_plural": "Columnas Kanban",
                "ordering": ["orden"],
            },
        ),
        migrations.AddField(
            model_name="environment",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entornos",
                to="projects.proyecto",
            ),
        ),
        migrations.CreateModel(
            name="Requerimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=30,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("nuevo", "Nuevo"),
                            ("analisis", "En análisis"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("implementado", "Implementado"),
                        ],
                        default="nuevo",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requerimientos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requerimientos",
                        to="projects.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Requerimiento",
                "verbose_name_plural": "Requerimientos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequerimientoArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("archivo", models.FileField(upload_to="requerimientos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requerimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="projects.requerimiento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos_requerimiento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de Requerimiento",
                "verbose_name_plural": "Archivos de Requerimiento",
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activo", models.BooleanField(default=False)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints",
                        to="projects.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprint",
                "verbose_name_plural": "Sprints",
                "ordering": ["fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Backlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=30,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backlog_items",
                        to="projects.proyecto",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backlog_items",
                        to="projects.sprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backlog",
                "verbose_name_plural": "Backlog Items",
                "ordering": ["orden", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_progreso", "En progreso"),
                            ("revision", "En revisión"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=50,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=30,
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "columna",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas",
                        to="projects.kanbancolumn",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="projects.proyecto",
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas",
                        to="projects.sprint",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["orden", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_archivo", models.CharField(max_length=255)),
                ("archivo", models.FileField(upload_to="tareas/archivos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos",
                        to="projects.task",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archivos_tarea",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo de Tarea",
                "verbose_name_plural": "Archivos de Tarea",
            },
        ),
        migrations.CreateModel(
            name="TaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="projects.task",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comentarios_tarea",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentario de Tarea",
                "verbose_name_plural": "Comentarios de Tarea",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=100)),
                ("valor_anterior", models.TextField(blank=True)),
                ("valor_nuevo", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="projects.task",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historial_tareas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Tarea",
                "verbose_name_plural": "Historial de Tareas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_lanzamiento", models.DateField(blank=True, null=True)),
                ("activa", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="projects.proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión",
                "verbose_name_plural": "Versiones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProyectoMiembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("lider", "Líder de proyecto"),
                            ("desarrollador", "Desarrollador"),
                            ("tester", "Tester"),
                            ("analista", "Analista"),
                            ("observador", "Observador"),
                        ],
                        default="desarrollador",
                        max_length=50,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="projects.proyecto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos_como_miembro",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Miembro del Proyecto",
                "verbose_name_plural": "Miembros del Proyecto",
                "unique_together": {("proyecto", "usuario")},
            },
        ),
    ]
